/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package formularios.tablas;

import clases.SQLiteCon;
import clases.Talonario;
import java.awt.Dimension;
import java.awt.Insets;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.threeten.bp.LocalDate;

/**
 *
 * @author junju
 */
public class tTimbrados extends javax.swing.JInternalFrame { 
 private SQLiteCon sqlite= new SQLiteCon();
 private Connection cn= sqlite.conectar();
 private String sSQL="";

 

    public tTimbrados() {
        initComponents();
        initDatePickers();
        mostrar();
        limpiartabla();
     
    }

 public DefaultTableModel mostrar(){
        DefaultTableModel modelo;
        
        String titulos[] = {"COMPROBANTE","SUCURSAL","P.EXPEDICION","NRO. DESDE","NRO.HASTA","FECHA DESDE","FECHA HASTA", "TIMBRADO"};
        String registro[]= new String[9];
        modelo= new DefaultTableModel(null,titulos);
        modelo.setRowCount(0);
        sSQL="Select * from talonarios";
        try{
            Statement st= cn.createStatement();
            ResultSet rs= st.executeQuery(sSQL);
            
            while(rs.next()){
                registro[0]= rs.getString("tipo_com");
                registro[1]= rs.getString("sucursal");
                registro[2]= rs.getString("punto_exp");
                registro[3]= rs.getString("nro_desde");       
                registro[4]= rs.getString("nro_hasta");
                registro[5]= rs.getString("fecha_des");
                registro[6]= rs.getString("fecha_has");
                registro[7]= rs.getString("timbrado");
                modelo.addRow(registro);
               
               
            } 
         //   System.out.println(" TRU " + Arrays.toString(registro));
            jTable1.setModel(modelo);
            return modelo;
        }
        catch(Exception e){
            JOptionPane.showConfirmDialog(null, e);
            return null;
            
        }
    
        
    }
 public void limpiartabla(){
  DefaultTableModel dtm=(DefaultTableModel) jTable1.getModel();
    int i=dtm.getRowCount();       
    for(int j=i-1;j>=0;j--)
         {

         if(!(jTable1.getValueAt(j, 0) != null 
         && jTable1.getValueAt(j, 0).toString().trim().length() != 0) )
         {
               dtm.removeRow(j);
         }

         }
 }
    
    
    
    private void initDatePickers(){
        // Limites de fechas
        Date now = new Date();
        LocalDate max = LocalDate.of(Calendar.getInstance().get(Calendar.YEAR)+10, 01, 01);
        LocalDate min = LocalDate.of(2010, 01, 01);

        // Fecha desde
        fechaDesde.getComponentDateTextField().setPreferredSize(new Dimension(80, 25));
        fechaDesde.getComponentToggleCalendarButton().setText("");
        fechaDesde.getComponentToggleCalendarButton().setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/ico/calendar.png"))); // NOI18N
        fechaDesde.getComponentToggleCalendarButton().setPreferredSize(new Dimension(25, 25));
        fechaDesde.getComponentDateTextField().setMargin(new Insets(0, 0, 0, 0));
        fechaDesde.getSettings().setFormatForDatesCommonEra("yyyy-MM-dd");
        fechaDesde.getSettings().setDateRangeLimits(min, max);
        
        // Fecha hasta
        fechaHasta.getComponentDateTextField().setPreferredSize(new Dimension(80, 25));
        fechaHasta.getComponentToggleCalendarButton().setText("");
        fechaHasta.getComponentToggleCalendarButton().setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/ico/calendar.png"))); // NOI18N
        fechaHasta.getComponentToggleCalendarButton().setPreferredSize(new Dimension(25, 25));
        fechaHasta.getComponentDateTextField().setMargin(new Insets(0, 0, 0, 0));
        fechaHasta.getSettings().setFormatForDatesCommonEra("yyyy-MM-dd");
        fechaHasta.getSettings().setDateRangeLimits(min, max);
    }
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBorrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboTC = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSucursal = new javax.swing.JTextField();
        txtPEX = new javax.swing.JTextField();
        txtDesde = new javax.swing.JTextField();
        txtHasta = new javax.swing.JTextField();
        txtTimbrado = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        fechaDesde = new com.github.lgooddatepicker.components.DatePicker();
        fechaHasta = new com.github.lgooddatepicker.components.DatePicker();
        txtid = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Talonarios");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo Comprobante", "Sucursal", "Punto de Expedicion", "Numero Desde", "Numero Hasta", "Fecha Desde", "Fecha Hasta", "Timbrado"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnBorrar.setText("Borrar");
        btnBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBorrarMousePressed(evt);
            }
        });
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBorrar)
                .addGap(6, 6, 6))
        );

        jTabbedPane1.addTab("Talonarios", jPanel1);

        jLabel1.setText("Tipo de Comprobante");
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 25));

        cboTC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 = Factura", "2 = Nota de Débito", "3 = Nota de Crédito", "4 = Despacho", "5 = Auto factura", "6 = Boleta de Venta", "7 = Pasaje Aéreo", "8 = Factura del Exterior", "9 = Planilla de Sueldos", "10 = Comprobante de Ingresos", "12 = Factura de Exportación", "11 = Retencion Absorvida", "13 = Pasaje Aéreo Electrónico" }));
        cboTC.setPreferredSize(new java.awt.Dimension(125, 25));

        jLabel2.setText("Sucursal");
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel3.setText("Punto de Expedición");
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel4.setText("Desde Número");
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel5.setText("Hasta Número");
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel6.setText("Fecha Inicio");
        jLabel6.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel7.setText("Fecha Final");
        jLabel7.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel8.setText("Timbrado");
        jLabel8.setPreferredSize(new java.awt.Dimension(150, 25));

        txtSucursal.setPreferredSize(new java.awt.Dimension(125, 25));

        txtPEX.setPreferredSize(new java.awt.Dimension(125, 25));

        txtDesde.setPreferredSize(new java.awt.Dimension(125, 25));

        txtHasta.setPreferredSize(new java.awt.Dimension(125, 25));

        txtTimbrado.setPreferredSize(new java.awt.Dimension(125, 25));

        jButton1.setText("Agregar");
        jButton1.setPreferredSize(new java.awt.Dimension(125, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        fechaDesde.setMinimumSize(null);
        fechaDesde.setPreferredSize(new java.awt.Dimension(125, 25));

        fechaHasta.setMinimumSize(null);
        fechaHasta.setPreferredSize(new java.awt.Dimension(125, 25));

        txtid.setEditable(false);
        txtid.setEnabled(false);
        txtid.setFocusable(false);
        txtid.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTimbrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPEX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 343, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPEX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimbrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("ABMc", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      mostrar();
      Connection c = null;
      Statement stmt = null;

      try {
                    Class.forName("org.sqlite.JDBC");
                    c = DriverManager.getConnection("jdbc:sqlite:Analytix.db");
                    System.out.println("Opened database successfully");

                    stmt = c.createStatement();
                    String sql = "INSERT INTO TALONARIOS VALUES(?,?,?,?,?,?,?,?);";
                    PreparedStatement preparedStmt = c.prepareStatement(sql);
                         //  int seleccionado = cboTC.getSelectedIndex();
                            
                           preparedStmt.setString(1, cboTC.getSelectedItem().toString());
                           preparedStmt.setString (2, txtSucursal.getText());
                           preparedStmt.setString (3, txtPEX.getText());
                           preparedStmt.setString (4, txtHasta.getText());
                           preparedStmt.setString (5, txtDesde.getText());
                           preparedStmt.setString (6, fechaDesde.getText());
                           preparedStmt.setString (7, fechaHasta.getText());
                           preparedStmt.setString (8, txtTimbrado.getText());

                           preparedStmt.execute(); 
                           JOptionPane.showMessageDialog(null, "Registro exitoso!");
                    stmt.executeUpdate(sql);
                    c.close();
                 } catch ( Exception e ) {
                    System.err.println( e.getClass().getName() + ": " + e.getMessage() );
                    System.exit(0);
                 }
                 System.out.println("Table created successfully");  // TODO code application logic here
      // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
    Connection c = null;
    int row = jTable1.getSelectedRow();
    DefaultTableModel model= (DefaultTableModel)jTable1.getModel();
    String selected = model.getValueAt(row, 0).toString();
           
                if (row > 0) {

                    model.removeRow(row);
                    model.removeRow(row);

                    try {
                         Class.forName("org.sqlite.JDBC");
             c = DriverManager.getConnection("jdbc:sqlite:Analytix.db");
                        PreparedStatement ps = c.prepareStatement("delete from talonarios where tipo_com='"+selected+"' ");
                        ps.executeUpdate();
                    }
                    catch (Exception w) {
                        JOptionPane.showMessageDialog(this, "Connection Error!");
                    }           
            }    // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnBorrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarMousePressed

        
    }//GEN-LAST:event_btnBorrarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JComboBox<String> cboTC;
    private com.github.lgooddatepicker.components.DatePicker fechaDesde;
    private com.github.lgooddatepicker.components.DatePicker fechaHasta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDesde;
    private javax.swing.JTextField txtHasta;
    private javax.swing.JTextField txtPEX;
    private javax.swing.JTextField txtSucursal;
    private javax.swing.JTextField txtTimbrado;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
   

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tTimbrados().setVisible(true);
            }
        });
    }

}
